### ISSUE TITLE
Post-Migration-Checklist

### ISSUE THREAD

**Issue by The-Compiler** [studentenportal/deploy2020#20]
Was sollte nun noch alles (im Rahmen vom momentanen Auftrag) erledigt werden, bevor wir dieses Kapitel abschliessen können? Hier mal meine Gedanken:

# Code

- [x] Im `web`-Repo nochmals ein komplettes Dependency-Upgrade machen (gab IIRC in Django letztens ein Security-Fix?)
- [x] gib-Solutions aus dem "powered by" rausnehmen, Bruhin Software (wie abgemacht) reinnehmen
- [x] `new.studentenportal.ch` loswerden (Code)
- [x] Ev. Flattr rausschmeissen (https://github.com/studentenportal/web/issues/246) wenn ich schon dabei bin - sollte keine grosse Sache sein.
- [x] deployment-Branch in den master mergen

# Deployment

- [x] systemd-Timer einrichten: https://github.com/studentenportal/deploy2020/issues/11
- [x] Gucken, dass die Docker-Container nach einem Reboot wieder automatisch sauber starten
- [x] Dieses Repo auf Public schalten
- [x] Das `deploy-new` Repo archivieren
- [x] Ein bisschen Dokumentation für das Deployment schreiben (zumindest für die Basics, z.B. wo die wichtigen Files liegen)
- [x] wip-Branch in den master mergen
- [x] `new.studentenportal.ch` loswerden (Ansible + DNS)
- [x] Mails einige Tage beobachten in der Hoffung, dass keine Error-Reports ankommen
- [x] Einmal alles neu deployen
- [x] TTL für studentenportal.ch wieder auf 3600 stellen

# Shutdown

- [x] Full-Disk Backup vom alten Server ziehen
- [x] @dbrgn Auf dem alten Server (old.studentenportal.ch) gibt es ein `/home/danilo` und `/home/dbargen`. Ich wollte da nicht selbst reingucken - guck also bitte, dass da nix mehr ist, was du noch brauchst und gib mir kurz Bescheid.
- [x] Alter Server herunterfahren (am besten nächsten Dienstag, dann ist er 2000 Tage durchgelaufen - darf ich? :laughing:)
- [x] gib-Solutions benachrichtigen

---

@fabianhauser @dbrgn Fällt euch noch mehr ein? Irgendwas, was weg soll? Sind ja alles Kleinigkeiten, sollte also keine grosse Sache mehr sein.

**Comment by The-Compiler** [comment]
@dbrgn Nochmals kurz einen Reminder: Guck bitte nach, ob auf dem Server in `/home/danilo` bzw. `/home/dbargen` nix mehr ist, was du brauchst. Ich würde dann am Dienstag den Server gerne herunterfahren, sofern's keinen guten Grund gibt, das (noch) nicht zu tun.

**Comment by dbrgn** [comment]
Oh, da sind noch alle kompromittierenden Informationen über die Dozenten gelagert :disappointed_relieved: 

---

Scherz beiseite, kann man plattmachen :slightly_smiling_face: Ich habe eigentlich nur noch dieses SQL-Script gefunden:

```sql
-- topquotes.sql
SELECT COUNT(*) cnt, v.vote, v.quote_id, q.quote, q.comment
FROM front_quotevote v LEFT JOIN front_quote
WHERE v.vote = 't'
GROUP BY v.quote_id, v.vote, q.quote, q.comment
HAVING count(*) > 10
ORDER BY cnt DESC;
```

...aber das kann auch weg :slightly_smiling_face: Backup vom Server hast du ja gezogen, oder?

Im Backup-Ordner (/var/backups/studentenportal/) hat's noch alte Backups seit 2012. Keine Ahnung ob da noch etwas wichtiges dabei ist.

@The-Compiler bitte warte mit dem Runterfahren noch bis Uptime-Tag 2000 und mach' dann einen Screenshot (ev. auch noch einen von den SMART-Warnungen). Wäre einen Tweet wert :slightly_smiling_face:

**Comment by The-Compiler** [comment]
> Backup vom Server hast du ja gezogen, oder?

Ja, ich hab mal ein komplettes Backup gezogen. Das kann von mir aus auch noch ne Weile bei mir rumdümpeln.

> @The-Compiler bitte warte mit dem Runterfahren noch bis Uptime-Tag 2000 und mach' dann einen Screenshot (ev. auch noch einen von den SMART-Warnungen). Wäre einen Tweet wert :slightly_smiling_face:

Exakt das hatte ich vor :laughing:

**Comment by The-Compiler** [comment]
![image](https://user-images.githubusercontent.com/625793/76837193-66c40f80-6832-11ea-9682-bfd151fd2479.png)

https://twitter.com/the_compiler/status/1239831837272309760

:tada: 

Fehlt also nur noch, gib-Solutions zu kontaktieren, ihnen für das jahrelange Sponsoring zu danken, und ihnen zu sagen, dass wir den Server nun nicht mehr brauchen. @fabianhauser @dbrgn wer von euch mag sich darüm kümmern? Ist vermutlich sinnvoller, wenn ihr das tut.

**Comment by dbrgn** [comment]
@fabianhauser willst du das übernehmen, als "offizieller" vom open\hsr?

**Comment by fabianhauser** [comment]
@dbrgn hast du hier noch E-Mails, auf die ich mich beziehen könnte?

**Comment by dbrgn** [comment]
@fabianhauser ich schicke dir die Infos.

**Comment by fabianhauser** [comment]
Das E-Mail ist raus - dieses Issue kann damit geschlossen werden 🙂
